/**
 * Internal dependencies
 */
import { cards, MollieTestData } from '../../../../resources';

export const checkoutEur: MollieTestData.PaymentStatus[] = [
	// {
	// 	testId: '',
	// 	gatewaySlug: 'applepay',
	// 	paymentStatus: 'paid',
	// 	orderStatus: 'processing',
	// },
	{
		testId: 'C420219',
		gatewaySlug: 'in3',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420220',
		gatewaySlug: 'in3',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420221',
		gatewaySlug: 'in3',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420222',
		gatewaySlug: 'in3',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C420230',
		gatewaySlug: 'bancontact',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420231',
		gatewaySlug: 'bancontact',
		paymentStatus: 'open',
		orderStatus: 'pending',
	},
	{
		testId: 'C420232',
		gatewaySlug: 'bancontact',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420233',
		gatewaySlug: 'bancontact',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420234',
		gatewaySlug: 'bancontact',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C420235',
		gatewaySlug: 'przelewy24',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420236',
		gatewaySlug: 'przelewy24',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420237',
		gatewaySlug: 'przelewy24',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420238',
		gatewaySlug: 'przelewy24',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	// {
	// 	testId: '',
	// 	gatewaySlug: 'voucher',
	// 	paymentStatus: 'expired',
	// 	orderStatus: 'pending',
	// },
	{
		testId: 'C420244',
		gatewaySlug: 'ideal',
		paymentStatus: 'paid',
		bankIssuer: 'ING',
		orderStatus: 'processing',
	},
	{
		testId: 'C420245',
		gatewaySlug: 'ideal',
		paymentStatus: 'open',
		bankIssuer: 'ING',
		orderStatus: 'pending',
	},
	{
		testId: 'C420246',
		gatewaySlug: 'ideal',
		paymentStatus: 'failed',
		bankIssuer: 'ING',
		orderStatus: 'pending',
	},
	{
		testId: 'C420248',
		gatewaySlug: 'ideal',
		paymentStatus: 'canceled',
		bankIssuer: 'ING',
		orderStatus: 'pending',
	},
	{
		testId: 'C420247',
		gatewaySlug: 'ideal',
		paymentStatus: 'expired',
		bankIssuer: 'ING',
		orderStatus: 'pending',
	},
	{
		testId: 'C420253',
		gatewaySlug: 'paypal',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420254',
		gatewaySlug: 'paypal',
		paymentStatus: 'pending',
		orderStatus: 'pending',
	},
	{
		testId: 'C420255',
		gatewaySlug: 'paypal',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420256',
		gatewaySlug: 'paypal',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420257',
		gatewaySlug: 'paypal',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	// {
	// 	testId: '',
	// 	gatewaySlug: 'giftcard',
	// 	paymentStatus: 'expired',
	// 	orderStatus: 'pending',
	// },
	{
		testId: 'C420260',
		gatewaySlug: 'eps',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420261',
		gatewaySlug: 'eps',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420262',
		gatewaySlug: 'eps',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420263',
		gatewaySlug: 'eps',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C420267',
		gatewaySlug: 'kbc',
		paymentStatus: 'paid',
		bankIssuer: 'KBC',
		orderStatus: 'processing',
	},
	{
		testId: 'C420264',
		gatewaySlug: 'kbc',
		paymentStatus: 'failed',
		bankIssuer: 'KBC',
		orderStatus: 'pending',
	},
	{
		testId: 'C420265',
		gatewaySlug: 'kbc',
		paymentStatus: 'canceled',
		bankIssuer: 'KBC',
		orderStatus: 'pending',
	},
	{
		testId: 'C420266',
		gatewaySlug: 'kbc',
		paymentStatus: 'expired',
		bankIssuer: 'KBC',
		orderStatus: 'pending',
	},
	{
		testId: 'C420268',
		gatewaySlug: 'creditcard',
		paymentStatus: 'paid',
		card: cards.visa,
		orderStatus: 'processing',
	},
	{
		testId: 'C420269',
		gatewaySlug: 'creditcard',
		paymentStatus: 'open',
		card: cards.visa,
		orderStatus: 'pending',
	},
	{
		testId: 'C420270',
		gatewaySlug: 'creditcard',
		paymentStatus: 'failed',
		card: cards.visa,
		orderStatus: 'pending',
	},
	// {
	// 	testId: 'C420272',
	// 	gatewaySlug: 'creditcard',
	// 	paymentStatus: 'canceled',
	// 	card: cards.visa,
	// 	orderStatus: 'pending',
	// },
	{
		testId: 'C420271',
		gatewaySlug: 'creditcard',
		paymentStatus: 'expired',
		card: cards.visa,
		orderStatus: 'pending',
	},
	{
		testId: 'C420284',
		gatewaySlug: 'banktransfer',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420283',
		gatewaySlug: 'banktransfer',
		paymentStatus: 'open',
		orderStatus: 'on-hold',
	},
	{
		testId: 'C420285',
		gatewaySlug: 'banktransfer',
		paymentStatus: 'expired',
		orderStatus: 'on-hold',
	},
	{
		testId: 'C420286',
		gatewaySlug: 'mybank',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420287',
		gatewaySlug: 'mybank',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420288',
		gatewaySlug: 'mybank',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420289',
		gatewaySlug: 'mybank',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C420298',
		gatewaySlug: 'belfius',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420299',
		gatewaySlug: 'belfius',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C420300',
		gatewaySlug: 'belfius',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420301',
		gatewaySlug: 'belfius',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C420302',
		gatewaySlug: 'billie',
		paymentStatus: 'authorized',
		orderStatus: 'processing',
		billingCompany: 'Syde',
	},
	{
		testId: 'C420303',
		gatewaySlug: 'billie',
		paymentStatus: 'failed',
		orderStatus: 'pending',
		billingCompany: 'Syde',
	},
	{
		testId: 'C420304',
		gatewaySlug: 'billie',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
		billingCompany: 'Syde',
	},
	{
		testId: 'C420305',
		gatewaySlug: 'billie',
		paymentStatus: 'expired',
		orderStatus: 'pending',
		billingCompany: 'Syde',
	},
	{
		testId: 'C420306',
		gatewaySlug: 'paysafecard',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C420307',
		gatewaySlug: 'paysafecard',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C420308',
		gatewaySlug: 'paysafecard',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007259',
		gatewaySlug: 'klarna',
		paymentStatus: 'authorized',
		orderStatus: 'processing',
	},
	{
		testId: 'C3007260',
		gatewaySlug: 'klarna',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007261',
		gatewaySlug: 'klarna',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007262',
		gatewaySlug: 'klarna',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007263',
		gatewaySlug: 'bancomatpay',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3007264',
		gatewaySlug: 'bancomatpay',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007265',
		gatewaySlug: 'bancomatpay',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3007266',
		gatewaySlug: 'bancomatpay',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3241643',
		gatewaySlug: 'alma',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3241644',
		gatewaySlug: 'alma',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3241645',
		gatewaySlug: 'alma',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3241646',
		gatewaySlug: 'alma',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3437846',
		gatewaySlug: 'trustly',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3437847',
		gatewaySlug: 'trustly',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3437848',
		gatewaySlug: 'trustly',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3437849',
		gatewaySlug: 'trustly',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622417',
		gatewaySlug: 'riverty',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3622418',
		gatewaySlug: 'riverty',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622419',
		gatewaySlug: 'riverty',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622420',
		gatewaySlug: 'riverty',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622429',
		gatewaySlug: 'payconiq',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3622430',
		gatewaySlug: 'payconiq',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622431',
		gatewaySlug: 'payconiq',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3622432',
		gatewaySlug: 'payconiq',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},
	{
		testId: 'C3757247',
		gatewaySlug: 'satispay',
		paymentStatus: 'paid',
		orderStatus: 'processing',
	},
	{
		testId: 'C3757248',
		gatewaySlug: 'satispay',
		paymentStatus: 'failed',
		orderStatus: 'pending',
	},
	{
		testId: 'C3757249',
		gatewaySlug: 'satispay',
		paymentStatus: 'canceled',
		orderStatus: 'pending',
	},
	{
		testId: 'C3757250',
		gatewaySlug: 'satispay',
		paymentStatus: 'expired',
		orderStatus: 'pending',
	},

	/**
	 * Deprecated gateways
	 */

	// {
	// 	testId: 'C420249',
	// 	gatewaySlug: 'klarnapaylater',
	// 	paymentStatus: 'authorized',
	// 	orderStatus: 'processing',
	// },
	// {
	// 	testId: 'C420250',
	// 	gatewaySlug: 'klarnapaylater',
	// 	paymentStatus: 'failed',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420251',
	// 	gatewaySlug: 'klarnapaylater',
	// 	paymentStatus: 'canceled',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420252',
	// 	gatewaySlug: 'klarnapaylater',
	// 	paymentStatus: 'expired',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420279',
	// 	gatewaySlug: 'klarnapaynow',
	// 	paymentStatus: 'authorized',
	// 	orderStatus: 'processing',
	// },
	// {
	// 	testId: 'C420280',
	// 	gatewaySlug: 'klarnapaynow',
	// 	paymentStatus: 'failed',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420281',
	// 	gatewaySlug: 'klarnapaynow',
	// 	paymentStatus: 'canceled',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420282',
	// 	gatewaySlug: 'klarnapaynow',
	// 	paymentStatus: 'expired',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420223',
	// 	gatewaySlug: 'klarnasliceit',
	// 	paymentStatus: 'authorized',
	// 	orderStatus: 'processing',
	// },
	// {
	// 	testId: 'C420224',
	// 	gatewaySlug: 'klarnasliceit',
	// 	paymentStatus: 'failed',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420225',
	// 	gatewaySlug: 'klarnasliceit',
	// 	paymentStatus: 'canceled',
	// 	orderStatus: 'pending',
	// },
	// {
	// 	testId: 'C420226',
	// 	gatewaySlug: 'klarnasliceit',
	// 	paymentStatus: 'expired',
	// 	orderStatus: 'pending',
	// },
];
