name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Test suite'
        required: true
        default: 'e2e:test:payment-api:smoke'
        type: choice
        options:
          - e2e:test:payment-api
          - e2e:test:payment-api:smoke
          - e2e:test:payment-api:refund
          - e2e:test:payment-api:multistep
          - e2e:test:payment-api:multistep:smoke
          - e2e:test:order-api
          - e2e:test:order-api:smoke
          - e2e:test:order-api:refund
          - e2e:test:order-api:multistep
          - e2e:test:order-api:multistep:smoke
      TESTRAIL_PLAN_ID:
        description: TestRail plan ID for reporting.
        required: false
        default: ''
        type: string
      TESTRAIL_RUN_ID:
        description: TestRail run ID for reporting.
        required: false
        default: ''
        type: string
#  pull_request:
#    branches: [dev/develop]
#    paths:
#      - 'src/**'
#      - 'lib/**'
#      - 'public/**'
#      - 'package.json'
#      - 'composer.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build tested plugin package
    uses: inpsyde/reusable-workflows/.github/workflows/build-and-distribute.yml@main
    secrets:
      GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
      GITHUB_USER_SSH_KEY: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
      GITHUB_USER_SSH_PUBLIC_KEY: ${{ secrets.DEPLOYBOT_SSH_PUBLIC_KEY }}
      NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_GITHUB_TOKEN_PACKAGES }}
    with:
      PACKAGE_NAME: mollie-payments-for-woocommerce
      NODE_VERSION: 22

  e2e-playwright:
    name: Run Playwright E2E Tests
    needs: build
    uses: inpsyde/reusable-workflows/.github/workflows/test-playwright.yml@fix/test-playwright
    with:
      PLAYWRIGHT_SCRIPT: ${{ inputs.TEST_SUITE }}
      PLAYWRIGHT_ARTIFACT_PATH: |
        artifacts/*
        playwright-report/
        test-results/
      PLAYWRIGHT_ARTIFACT_INCLUDE_HIDDEN_FILES: true
      NODE_VERSION: 24
      PLAYWRIGHT_BROWSER_ARGS: 'chromium --with-deps'
      NGROK_DOMAIN: ngrok-dev.mollie.syde.wpinfra.cloud
      TESTRAIL_PLAN_ID: ${{ inputs.TESTRAIL_PLAN_ID }}
      TESTRAIL_RUN_ID: ${{ inputs.TESTRAIL_RUN_ID }}
      
      PRE_SCRIPT: |
        # 1. Download and unzip the built plugin
        gh run download ${{ github.run_id }} -p "mollie-payments-for-woocommerce-*" -D tests/qa/resources/files
        (
          cd tests/qa/resources/files
          mv mollie-payments-for-woocommerce-*/mollie-payments-for-woocommerce .
          zip -rq mollie-payments-for-woocommerce.zip mollie-payments-for-woocommerce
          rm -rf mollie-payments-for-woocommerce mollie-payments-for-woocommerce-*/
        )

        # 2. Add private composer repository and download WooCommerce Subscriptions and Germanized Pro
        composer config repositories.repo-name composer https://repo.packagist.com/inpsyde/payment-gateways/
        composer require inpsyde-mirror/woocommerce-subscriptions
        composer require inpsyde-mirror/woocommerce-germanized-pro
    secrets:
      ENV_FILE_DATA: ${{ secrets.ENV_FILE_DATA }}
      NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_GITHUB_TOKEN_PACKAGES }}
      COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
