name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      TEST_SUITE:
        description: 'Test suite'
        required: true
        default: 'e2e:test:payment-api:smoke'
        type: choice
        options:
          - e2e:test:payment-api
          - e2e:test:payment-api:smoke
          - e2e:test:payment-api:refund
          - e2e:test:payment-api:multistep
          - e2e:test:payment-api:multistep:smoke
          - e2e:test:order-api
          - e2e:test:order-api:smoke
          - e2e:test:order-api:refund
          - e2e:test:order-api:multistep
          - e2e:test:order-api:multistep:smoke
#  pull_request:
#    branches: [dev/develop]
#    paths:
#      - 'src/**'
#      - 'lib/**'
#      - 'public/**'
#      - 'package.json'
#      - 'composer.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-playwright:
    name: Run Playwright E2E Tests
    needs: build
    uses: inpsyde/reusable-workflows/.github/workflows/test-playwright.yml@fix/test-playwright
    with:
      PLAYWRIGHT_SCRIPT: ${{ inputs.TEST_SUITE }}
      ARTIFACT_PATH: |
        artifacts/*
        playwright-report/
        test-results/
      ARTIFACT_INCLUDE_HIDDEN_FILES: true
      NODE_VERSION: 24
      PLAYWRIGHT_BROWSER_ARGS: 'chromium --with-deps'
      NGROK_DOMAIN: ngrok-dev.mollie.syde.wpinfra.cloud
      
      PRE_SCRIPT: |
        # 1. Download the latest built plugin from build-and-distribute workflow
        RUN_ID=$(gh run list \
          --workflow=release.yml \
          --branch="${GITHUB_REF_NAME}" \
          --status=success \
          --limit=1 \
          --json databaseId \
          -q '.[0].databaseId')

        if [ -z "$RUN_ID" ]; then
          echo "::error::No successful build-and-distribute run found on branch ${GITHUB_REF_NAME}"
          exit 1
        fi

        echo "Downloading artifact from run $RUN_ID"
        gh run download "$RUN_ID" \
          -p "mollie-payments-for-woocommerce-*" \
          -D tests/qa/resources/files
        (
          cd tests/qa/resources/files
          mv mollie-payments-for-woocommerce-*/mollie-payments-for-woocommerce .
          zip -rq mollie-payments-for-woocommerce.zip mollie-payments-for-woocommerce
          rm -rf mollie-payments-for-woocommerce mollie-payments-for-woocommerce-*/
        )

        # 2. Add private composer repository and download WooCommerce Subscriptions and Germanized Pro
        composer config repositories.repo-name composer https://repo.packagist.com/inpsyde/payment-gateways/
        composer require inpsyde-mirror/woocommerce-subscriptions
        composer require inpsyde-mirror/woocommerce-germanized-pro
    secrets:
      ENV_FILE_DATA: ${{ secrets.ENV_FILE_DATA }}
      NPM_REGISTRY_TOKEN: ${{ secrets.DEPLOYBOT_GITHUB_TOKEN_PACKAGES }}
      COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
