name: Create release package
on:
  workflow_dispatch:
    inputs:
      PACKAGE_VERSION:
        description: 'Package Version'
        required: false
jobs:
  create_archive:
    uses: inpsyde/reusable-workflows/.github/workflows/build-and-distribute.yml@main
    secrets:
      GITHUB_USER_EMAIL: ${{ secrets.DEPLOYBOT_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.DEPLOYBOT_USER }}
      GITHUB_USER_SSH_KEY: ${{ secrets.DEPLOYBOT_SSH_PRIVATE_KEY }}
      GITHUB_USER_SSH_PUBLIC_KEY: ${{ secrets.DEPLOYBOT_SSH_PUBLIC_KEY }}
    with:
      PACKAGE_NAME: mollie-payments-for-woocommerce
      PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION }}
