export const ACTIONS = {
	// Field updates
	SET_SELECTED_ISSUER: 'SET_SELECTED_ISSUER',
	SET_INPUT_PHONE: 'SET_INPUT_PHONE',
	SET_INPUT_BIRTHDATE: 'SET_INPUT_BIRTHDATE',
	SET_INPUT_COMPANY: 'SET_INPUT_COMPANY',

	// Payment method state
	SET_ACTIVE_PAYMENT_METHOD: 'SET_ACTIVE_PAYMENT_METHOD',
	SET_PAYMENT_ITEM_DATA: 'SET_PAYMENT_ITEM_DATA',

	// Configuration
	SET_REQUIRED_FIELDS: 'SET_REQUIRED_FIELDS',
	SET_PHONE_FIELD_VISIBLE: 'SET_PHONE_FIELD_VISIBLE',
	SET_BILLING_DATA: 'SET_BILLING_DATA',
	SET_SHIPPING_DATA: 'SET_SHIPPING_DATA',

	// Validation
	SET_VALIDATION_STATE: 'SET_VALIDATION_STATE',

	// Country settings
	SET_PHONE_PLACEHOLDER: 'SET_PHONE_PLACEHOLDER',

	// Credit card
	SET_CARD_TOKEN: 'SET_CARD_TOKEN',
};
